owner: xDoofy92
repo: status

sites:
  - name: DProjects
    url: https://www.dprojects.org

  - name: API DProjects
    url: https://api.dprojects.org/api/ping
    body: pong
    
  - name: xdoofy92
    url: https://xdoofy92.com
    
  - name: MiniOS
    url: https://minios.org
    body: pong
    
status-website:
  theme: night
  cname: status.xdoofy92.com
  favicon: https://xdoofy92.com/statusicon.svg
  logoUrl: https://xdoofy92.com/statusicon.svg
  name: Status
  introTitle: "Estado de **servicios** en tiempo real"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Telegram
      href: https://t.me/dprojects
