owner: xDoofy92
repo: status

sites:
  - name: DProjects
    url: https://www.dprojects.org
  - name: API DProjects
    url: https://api.dprojects.org/api/ping
    body: pong
  - name: WKeys
    url: https://wkeys.net/api/ping
    body: pong
  - name: Torrent Seed
    url: pw.wkeys.net
    port: 51413
    check: "tcp-ping"
    assignees:
      - CarmeloCampos

status-website:
  theme: night
  cname: status.dprojects.org
  favicon: https://www.dprojects.org/icon.webp
  logoUrl: https://api.dprojects.org/logo.png
  name: DProjects Status
  introTitle: "Estado de **DProjects y Servicios** en tiempo real"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Telegram
      href: https://t.me/dprojects
